version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: frontend-portal-boa-entrega
        BUILD_FOLDER: dist/boa-entrega-portal
        BUILD_ENV: "prod"
phases:
    install:
        runtime-versions:
          nodejs: 14
        commands:
            - cd frontend-portal-boa-entrega
            - npm install
            - npm install -g @angular/cli
            - npm install -g @angular/core
    build:
        commands:
            - echo Build started on `date`
            - ng build
    post_build:
         commands:
            - aws s3 cp ${BUILD_FOLDER} s3://${S3_BUCKET} --recursive --acl public-read --cache-control "max-age=${CACHE_CONTROL}"
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    discard-paths: no
